ocilib:
  generator: builtin-github

  defaults:
    github:
      user: vrogier

    category: dev-db
    template: "templates/simple-github.tmpl"
    vars:
      rdepend: |
        dev-db/oracle-instantclient-basic
      depend: |
        ${RDEPEND}
        dev-db/oracle-instantclient-sdk
      body: |
        src_compile() {
          local myconf="${myconf} "
          local oracle_version=$(best_version dev-db/oracle-instantclient-basic \
            | sed -e 's/dev-db\/oracle-instantclient-basic-//')

          einfo "Use oracle version ${oracle_version}"
          myconf="${myconf} --enable-shared"

          myconf="${myconf} \
              --with-oracle-headers-path=/usr/lib64/oracle/${oracle_version}/client/include"
          myconf="${myconf} \
              --with-oracle-lib-path=/usr/lib64/oracle/${oracle_version}/client/lib"

          myconf="${myconf} \
              --with-oracle-home=/usr/lib64/oracle/${oracle_version}/client/"

          econf ${myconf} || die
          emake || die
        }
        src_install() {
          make install DESTDIR="${D}" || die "install failed"
        }

  packages:

    - ocilib:

    - ocilib:
        selector:
          - '=4.7.6'

    - ocilib:
        selector:
          - '=4.6.0'

