# Copyright 1999-2006 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# This ebuild generated by g-cpan 0.15.0

inherit perl-module

S=${WORKDIR}/Any-Moose-0.10

DESCRIPTION="No description available"
HOMEPAGE="http://search.cpan.org/search?query=Any-Moose&mode=dist"
SRC_URI="mirror://cpan/authors/id/S/SA/SARTAK/Any-Moose-0.10.tar.gz"


IUSE=""

SLOT="0"
LICENSE="|| ( Artistic GPL-2 )"
KEYWORDS="amd64"

DEPEND="dev-lang/perl"
