# Copyright 1999-2006 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# This ebuild generated by g-cpan 0.15.0

inherit perl-module

S=${WORKDIR}/Catalyst-Controller-HTML-FormFu-0.04003

DESCRIPTION="No description available"
HOMEPAGE="http://search.cpan.org/search?query=Catalyst-Controller-HTML-FormFu&mode=dist"
SRC_URI="mirror://cpan/authors/id/C/CF/CFRANKS/Catalyst-Controller-HTML-FormFu-0.04003.tar.gz"


IUSE=""

SLOT="0"
LICENSE="|| ( Artistic GPL-2 )"
KEYWORDS="amd64"

DEPEND=">=perl-gcpan/Catalyst-Plugin-ConfigLoader-0.23
	perl-gcpan/Catalyst-Plugin-Session-State-Cookie
	dev-perl/config-general
	perl-gcpan/Config-Any
	perl-gcpan/Test-WWW-Mechanize-Catalyst
	dev-perl/Task-Weaken
	>=dev-perl/MRO-Compat-0.10
	dev-perl/Moose
	perl-gcpan/Regexp-Assemble
	perl-gcpan/Catalyst-View-TT
	>=perl-gcpan/HTML-FormFu-0.04002
	perl-gcpan/Catalyst-Plugin-Session-Store-File
	dev-perl/Template-Toolkit
	perl-gcpan/Catalyst-Plugin-Session
	perl-gcpan/Catalyst-Action-RenderView
	perl-gcpan/Catalyst-Component-InstancePerContext
	perl-gcpan/Catalyst-Runtime
	>=dev-perl/Test-WWW-Mechanize-1.24
	dev-lang/perl"
