#!/sbin/runscript

depend() {
  need net
}

start() {
  ebegin "Starting ArangoDB v3"
  start-stop-daemon \
    --start \
    --exec /usr/sbin/arangod \
    --pidfile /var/run/arangod3.pid \
    --make-pidfile \
    --user arangodb3 \
    --background
  eend $? "Failed to start ArangoDB v3"
}

stop() {
  ebegin "Stopping ArangoDB v3"
  start-stop-daemon --stop --pidfile /var/run/arangod3.pid
  eend $? "Failed to stop ArangoDB v3"
}
