# Copyright 1999-2006 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# This ebuild generated by g-cpan 0.15.0

inherit perl-module

S=${WORKDIR}/Regexp-Assemble-0.34

DESCRIPTION="Combine patterns into single pattern"
HOMEPAGE="http://search.cpan.org/search?query=Regexp-Assemble&mode=dist"
SRC_URI="mirror://cpan/authors/id/D/DL/DLAND/Regexp-Assemble-0.34.tar.gz"


IUSE=""

SLOT="0"
LICENSE="|| ( Artistic GPL-2 )"
KEYWORDS="amd64"

