# Copyright 1999-2006 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# This ebuild generated by g-cpan 0.15.0

inherit perl-module

S=${WORKDIR}/SWF-Chart-1.4

DESCRIPTION="No description available"
HOMEPAGE="http://search.cpan.org/search?query=SWF-Chart&mode=dist"
SRC_URI="mirror://cpan/authors/id/G/GA/GARTH/SWF-Chart-1.4.tar.gz"


IUSE=""

SLOT="0"
LICENSE="|| ( Artistic GPL-2 )"
KEYWORDS="amd64"

