# Copyright 1999-2006 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# This ebuild generated by g-cpan 0.15.0

inherit perl-module

S=${WORKDIR}/HTTP-Body-1.05

DESCRIPTION="HTTP Body Parser"
HOMEPAGE="http://search.cpan.org/search?query=HTTP-Body&mode=dist"
SRC_URI="mirror://cpan/authors/id/A/AG/AGRUNDMA/HTTP-Body-1.05.tar.gz"


IUSE=""

SLOT="0"
LICENSE="|| ( Artistic GPL-2 )"
KEYWORDS="amd64"

DEPEND="dev-perl/yaml
	dev-perl/libwww-perl
	dev-lang/perl"
