# Copyright 1999-2006 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# This ebuild generated by g-cpan 0.15.0

inherit perl-module

S=${WORKDIR}/Scope-Upper-0.09

DESCRIPTION="Act on upper scopes."
HOMEPAGE="http://search.cpan.org/search?query=Scope-Upper&mode=dist"
SRC_URI="mirror://cpan/authors/id/V/VP/VPIT/Scope-Upper-0.09.tar.gz"


IUSE=""

SLOT="0"
LICENSE="|| ( Artistic GPL-2 )"
KEYWORDS="amd64"

DEPEND="dev-lang/perl"
