# Copyright 1999-2019 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2
# Ebuild automatically produced by node-ebuilder.

EAPI=6

DESCRIPTION="Translate symbol names generated by --basic-perf-prof into JavaScript names"
HOMEPAGE="https://github.com/davidmarkclements/perf-sym#readme"

LICENSE="MIT"
SLOT="0"
KEYWORDS="*"
IUSE=""

DEPEND="
	>=dev-node/end-of-stream-1.4.1
	>=dev-node/minimist-1.2.0
	>=dev-node/pump-1.0.3
	>=dev-node/resolve-jit-symbols-0.5.0
	>=dev-node/split2-2.1.1
"
RDEPEND="${DEPEND}"

NPM_NO_DEPS=1

S="${WORKDIR}/package"

inherit npmv1

