# Copyright 1999-2010 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# This ebuild generated by g-cpan 0.16.0

EAPI="2"

MODULE_AUTHOR="AFF"

inherit perl-module

DESCRIPTION="Create SQL for Oracle."

LICENSE="|| ( Artistic GPL-1 GPL-2 GPL-3 )"
SLOT="0"
KEYWORDS="amd64"
IUSE=""

DEPEND="perl-gcpan/Text-Table
	virtual/perl-IO-Compress
	dev-perl/Test-Exception
	dev-perl/XML-DOM
	dev-perl/Log-Log4perl
	dev-lang/perl"
