# Copyright 1999-2006 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# This ebuild generated by g-cpan 0.15.0

inherit perl-module

S=${WORKDIR}/Test-MockTime-0.12

DESCRIPTION="Mock time/localtime for testing"
HOMEPAGE="http://search.cpan.org/search?query=Test-MockTime&mode=dist"
SRC_URI="mirror://cpan/authors/id/D/DD/DDICK/Test-MockTime-0.12.tar.gz"


IUSE=""

SLOT="0"
LICENSE="|| ( Artistic GPL-2 )"
KEYWORDS="amd64"

DEPEND="virtual/perl-Time-Piece
	dev-lang/perl"
