# Copyright 1999-2006 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# This ebuild generated by g-cpan 0.15.0

inherit perl-module

S=${WORKDIR}/autobox-2.55

DESCRIPTION="No description available"
HOMEPAGE="http://search.cpan.org/search?query=autobox&mode=dist"
SRC_URI="mirror://cpan/authors/id/C/CH/CHOCOLATE/autobox-2.55.tar.gz"


IUSE=""

SLOT="0"
LICENSE="|| ( Artistic GPL-2 )"
KEYWORDS="amd64"

DEPEND=">=dev-perl/Scope-Guard-0.03
	dev-lang/perl"
