# Copyright 1999-2006 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# This ebuild generated by g-cpan 0.15.0

inherit perl-module

S=${WORKDIR}/Mouse-0.27

DESCRIPTION="No description available"
HOMEPAGE="http://search.cpan.org/search?query=Mouse&mode=dist"
SRC_URI="mirror://cpan/authors/id/S/SA/SARTAK/Mouse-0.27.tar.gz"


IUSE=""

SLOT="0"
LICENSE="|| ( Artistic GPL-2 )"
KEYWORDS="amd64"

DEPEND=">=dev-perl/Test-Exception-0.27
	dev-lang/perl"
