# Copyright 1999-2006 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# This ebuild generated by g-cpan 0.15.0

inherit perl-module

S=${WORKDIR}/Task-Catalyst-Tutorial-0.06

DESCRIPTION="install Catalyst Tutorial + dependencies"
HOMEPAGE="http://search.cpan.org/search?query=Task-Catalyst-Tutorial&mode=dist"
SRC_URI="mirror://cpan/authors/id/M/MR/MRAMBERG/Task-Catalyst-Tutorial-0.06.tar.gz"


IUSE=""

SLOT="0"
LICENSE="|| ( Artistic GPL-2 )"
KEYWORDS="amd64"

DEPEND="perl-gcpan/Catalyst-Devel
	>=perl-gcpan/Catalyst-Plugin-Authorization-ACL-0.11
	>=perl-gcpan/Catalyst-Plugin-Session-Store-FastMmap-0.09
	>=perl-gcpan/Catalyst-Plugin-Session-State-Cookie-0.10
	>=perl-gcpan/Catalyst-Plugin-Authorization-Roles-0.07
	>=perl-gcpan/Catalyst-Controller-HTML-FormFu-0.04003
	perl-gcpan/DBIx-Class
	>=perl-gcpan/Catalyst-Authentication-Store-DBIx-Class-0.1082
	>=perl-gcpan/Catalyst-View-TT-0.29
	>=perl-gcpan/Catalyst-Manual-5.7021
	>=perl-gcpan/Catalyst-Plugin-StackTrace-0.10
	perl-gcpan/Catalyst-Plugin-Session
	>=perl-gcpan/Catalyst-Model-DBIC-Schema-0.23
	>=perl-gcpan/Catalyst-Plugin-Authentication-0.10011
	perl-gcpan/Catalyst-Runtime
	dev-lang/perl"
