# Copyright 1999-2006 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# This ebuild generated by g-cpan 0.15.0

inherit perl-module

S=${WORKDIR}/Log-Trace-1.070

DESCRIPTION="No description available"
HOMEPAGE="http://search.cpan.org/search?query=Log-Trace&mode=dist"
SRC_URI="mirror://cpan/authors/id/B/BB/BBC/Log-Trace-1.070.tar.gz"


IUSE=""

SLOT="0"
LICENSE="|| ( Artistic GPL-2 )"
KEYWORDS="amd64"

DEPEND="dev-lang/perl"
