# Copyright 1999-2019 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2
# Ebuild automatically produced by node-ebuilder.

EAPI=6

DESCRIPTION="Resolves symbols for dynamic code generated by a JIT via a map file."
HOMEPAGE="https://github.com/thlorenz/resolve-jit-symbols"

LICENSE="[object Object]"
SLOT="0"
KEYWORDS="*"
IUSE=""

DEPEND="
	>=dev-node/pretty-trace-0.3.1
"
RDEPEND="${DEPEND}"

NPM_NO_DEPS=1

S="${WORKDIR}/package"

inherit npmv1

