# Copyright 1999-2006 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# This ebuild generated by g-cpan 0.15.0

inherit perl-module

S=${WORKDIR}/Cache-FastMmap-1.30

DESCRIPTION="No description available"
HOMEPAGE="http://search.cpan.org/search?query=Cache-FastMmap&mode=dist"
SRC_URI="mirror://cpan/authors/id/R/RO/ROBM/Cache-FastMmap-1.30.tar.gz"


IUSE=""

SLOT="0"
LICENSE="|| ( Artistic GPL-2 )"
KEYWORDS="amd64"

DEPEND="dev-lang/perl"
